-- Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
__console = {log = print};

Block = require "block";

function to_string(e) do
  local ___conditional___=(e.tag | 0);
  do
     if ___conditional___ == 0--[[ Plus ]] then do
        return "(" .. (to_string(e[1]) .. (" + " .. (to_string(e[2]) .. ")"))); end end 
     if ___conditional___ == 1--[[ Minus ]] then do
        return "(" .. (to_string(e[1]) .. (" - " .. (to_string(e[2]) .. ")"))); end end 
     if ___conditional___ == 2--[[ Times ]] then do
        return "(" .. (to_string(e[1]) .. (" * " .. (to_string(e[2]) .. ")"))); end end 
     if ___conditional___ == 3--[[ Divide ]] then do
        return "(" .. (to_string(e[1]) .. (" / " .. (to_string(e[2]) .. ")"))); end end 
     if ___conditional___ == 4--[[ Value ]] then do
        return e[1]; end end 
    
  end
end end

function print_expr(e) do
  __console.log(to_string(e));
  return --[[ () ]]0;
end end

__console.log(to_string(--[[ Times ]]Block.__(2, {
            --[[ Value ]]Block.__(4, {"n"}),
            --[[ Plus ]]Block.__(0, {
                --[[ Value ]]Block.__(4, {"x"}),
                --[[ Divide ]]Block.__(3, {
                    --[[ Value ]]Block.__(4, {"y"}),
                    --[[ Minus ]]Block.__(1, {
                        --[[ Value ]]Block.__(4, {"z"}),
                        --[[ Value ]]Block.__(4, {"w"})
                      })
                  })
              })
          })));

exports = {};
exports.to_string = to_string;
exports.print_expr = print_expr;
return exports;
--[[  Not a pure module ]]
